title: LeicsHack 2022
nav_title: LeicsHack<span class="hide-very-narrow"> 2022</span><br><small><span class="hide-very-narrow">at</span> University of Leicester</small>

event_date: 26–27 March 2022
registration_opens_date: 3 February 2022
registration_closes_date: 11 March 2022

author: LeicsHack at University of Leicester
mailbox_address: mathewfitzgerald00@gmail.com

description:
  LeicsHack (pronounced let's hack!) 2022 finally brings hackathons to Leicester! 
  LeicsHack is a 24 hour hackathon challenging student coders of all skill levels from all 
  universities to create and innovate while having fun. We will provide food for duration of the hack 
  (but bring extra snacks and water!), somewhere to sleep, and games for when you need a break. Let's Hack!

url: "leicshack.com"
github_repo: spooky21squid/LeicsHack

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - registration.md
  - agenda.md
  - projects.md
  - videos-slides.md
  - resources.md
  - about.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: soon

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: open

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
